server.address=127.0.0.1
server.port=${PORT:8080}
spring.application.name=ten-year-futures
spring.jackson.serialization.write-dates-as-timestamps=false
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.error.include-message=always
report.data-dir=${REPORT_DATA_DIR:./data}
report.output-path=${REPORT_OUTPUT_PATH:D:/Download/gold/d1cb4da4-d727-4a9b-a786-befda4c43b3c/_4883x2900.png}
